<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $guarded = [];

    protected $casts = [
        'completed' => 'boolean'
    ];

    protected $touches = ['project'];

    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    public function path()
    {
        return "/projects/{$this->project->id}/tasks/{$this->id}";
    }

    protected  static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

    }

    public function complete()
    {
        $this->update(['completed' => true]);

        $this->recordActivity('completed_task');
    }

    public function incomplete()
    {
        $this->update(['completed' => false]);

        $this->recordActivity('uncompleted_task');
    }


    public function recordActivity($description)
    {

        $this->activity()->create([
            'project_id' => $this->project->id,
            'description'=> $description
        ]);

    }

    public function activity()
    {
        return $this->morphMany(Activity::class, 'subject')->latest();
    }
}
