<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $guarded = [];

    protected $casts = [
        'completed' => 'boolean'
    ];

    protected $touches = ['project'];

    public function project()
    {
        return $this->belongsTo(Project::class);
    }

    public function path()
    {
        return "/projects/{$this->project->id}/tasks/{$this->id}";
    }

    protected  static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($task){

            $task->project->recordActivity('created_task');
        });


        static::updated(function ($task){
            if(!$task->completed) return;

            $task->project->recordActivity('completed_task');

        });
    }

    public function complete()
    {
        $this->update(['completed' => true]);
    }
}
